version: '3.8'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # 请修改为自己的密码
      MYSQL_ROOT_PASSWORD: 123456
      TZ: 'Asia/Shanghai'
    # ports:
    #   - 3306:3306

  server:
    image: cooderl/wewe-rss-server:latest
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      # 数据库连接地址
      - DATABASE_URL="mysql://root:123456@db:3306/wewe-rss"
      # 服务接口请求授权码
      - AUTH_CODE="123567"
      # 服务接口请求限制，每分钟请求次数
      - MAX_REQUEST_PER_MINUTE=60
      # 外网访问时，需设置为服务器的公网 IP 或者域名地址
      - SERVER_ORIGIN_URL=http://localhost:4000

  web:
    image: cooderl/wewe-rss-web:latest
    ports:
      - 3000:3000
    environment:
      # 同 SERVER_ORIGIN_URL
      - NEXT_PUBLIC_SERVER_ORIGIN_URL=http://localhost:4000

networks:
  wewe-rss:
