name: Build WeWeRSS images and push image to docker hub
on:
  workflow_dispatch:
  push:
    paths:
      - "apps/**"
      - "Dockerfile"
    tags:
      - "v*.*.*"

concurrency:
  group: docker-release
  cancel-in-progress: true

jobs:
  check-env:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      check-docker: ${{ steps.check-docker.outputs.defined }}
    steps:
      - id: check-docker
        env:
          DOCKER_HUB_NAME: ${{ secrets.DOCKER_HUB_NAME }}
        if: ${{ env.DOCKER_HUB_NAME != '' }}
        run: echo "defined=true" >> $GITHUB_OUTPUT

  release-images:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (web)
        id: meta-web
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_HUB_NAME }}/wewe-rss-web
            ghcr.io/cooderl/wewe-rss-web
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=${{ github.ref_name }},enable=true
          flavor: latest=false

      - name: Build and push Docker image (web)
        id: build-and-push-web
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
          target: web
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=docker-release
          cache-to: type=gha,mode=max,scope=docker-release

      - name: Extract Docker metadata (server)
        id: meta-server
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_HUB_NAME }}/wewe-rss-server
            ghcr.io/cooderl/wewe-rss-server
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=${{ github.ref_name }},enable=true
          flavor: latest=false

      - name: Build and push Docker image (server)
        id: build-and-push-server
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}
          target: server
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=docker-release
          cache-to: type=gha,mode=max,scope=docker-release

  description:
    runs-on: ubuntu-latest
    needs: check-env
    if: needs.check-env.outputs.check-docker == 'true'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description(web)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_NAME }}/wewe-rss-web

      - name: Docker Hub Description(server)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_NAME }}/wewe-rss-server
